[package]
name = "addition"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
tonic = "0.12.3"
prost = "0.13.4"
tokio = { version = "1.43.0", features = ["full"] }
tonic-reflection = "0.12.3"

[build-dependencies]
tonic-build = "0.12.3"
